import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Issue Hub",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/bookIssueHubIcon1.svg" sizes="any"/>
      </head>
      <body className={`${inter.className}, font-serif`}>
        <Toaster position="bottom-center" richColors closeButton />
        {children}
      </body>
    </html>
  );
}
